language: php

services: mysql

php: 7.1

cache:
    directories:
    - node_modules
    - vendor

before_script:
  - composer install
  - npm install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('tablutpw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  # Code style & syntax linters
  - composer check-php
  - npm run lint-css
  - npm run lint-js

  # Unit tests
  - npm test
  # Note: the PHP tests require a running MySQL DB with its corresponding config set in bgaproject.yml
  - cp bgaproject.yml.dist bgaproject.yml
  - composer test

  # BGA-specific checks
  # (note: `deploy` could be enabled by generating `bgaproject.yml` from TravisCI secrets)
  - composer bgaw-validate
  - composer bgaw-clean
  - composer bgaw-build

notifications:
  email:
    on_success: never