language: php

dist: trusty
sudo: false

services:
  - mysql

php:
  - 7.1

before_script:
  - npm install eslint eslint-config-strict eslint-plugin-filenames
  - composer install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('tablutpw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - node_modules/.bin/eslint tablut.js

  - composer check-styles
  - composer test

  - cp bgaproject.yml.dist bgaproject.yml
  - composer bgaw-clean
  - composer bgaw-build
  - composer bgaw-validate
