language: php

dist: trusty
sudo: false

services:
  - mysql

php:
  - 7.1

before_script:
  - npm config set proxy null
  - npm config set https-proxy null
  - npm config set strict-ssl false
  - npm install -g eslineslint eslint-config-strict eslint-plugin-filenames
  - composer install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('tablutpw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - eslint tablut.js
  - composer clean
  - composer build
  - composer bga-validate
  - composer check-styles
  - composer test
