language: php

services: mysql

php: 7.1

before_script:
  - npm install -g csslint eslint eslint-config-strict eslint-plugin-filenames
  - composer install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('tablutpw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  # Code style & syntax linters
  - composer check-styles

  # Unit tests
  - composer test

  # BGA-specific checks
  - cp bgaproject.yml.dist bgaproject.yml
  - composer bgaw-clean
  - composer bgaw-build
  - composer bgaw-validate
