language: php

services: mysql

php: 7.1

before_script:
  - composer install
  - npm install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('tablutpw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  # Code style & syntax linters
  - composer check-php
  - npm lint-css
  - npm lint-js

  # Unit tests
  - composer test
  - npm test

  # BGA-specific checks
  - cp bgaproject.yml.dist bgaproject.yml
  - composer bgaw-clean
  - composer bgaw-build
  - composer bgaw-validate
